name = "rupert"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Rupert"]

[leanOptions]
experimental.module = true
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Rupert"
